name: ibvse
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - matplotlib
  - numpy
  - tqdm
  - future
  - tensorboard>=2.0.0
  - pandas
  - faiss=1.7.2
  - imageio
  - scikit-learn
  - scikit-image
  - plotly
  - optuna
  - pip
  - pip:
      - argparse
      - hnswlib
      - annoy
      - opencv-python
      - PyQt5
